# Generated by Django 4.2.7 on 2023-11-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('Parks', 'Parks'), ('Lakes', 'Lakes'), ('Forts', 'Forts'), ('Temples', 'Temples'), ('Dineout', 'Dineout'), ('Viewpoints', 'Viewpoints')], max_length=100)),
            ],
        ),
    ]
